apiVersion: v1
kind: Secret
metadata:
  name: "vc-config-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ include "vcluster.version.label"  $ }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.controlPlane.advanced.globalMetadata.annotations }}
  annotations:
{{ toYaml .Values.controlPlane.advanced.globalMetadata.annotations | indent 4 }}
  {{- end }}
type: Opaque
{{ $config := deepCopy .Values }}
{{ $_ := unset $config.controlPlane.statefulSet.security "profile" }}
{{ $_ := unset $config.controlPlane.backingStore.etcd.deploy.statefulSet.security "profile" }}
{{- if and (hasKey $config "coredns") (hasKey $config.coredns "security") }}
{{ $_ := unset $config.coredns.security "profile" }}
{{- end }}
data:
  config.yaml: {{ $config | toYaml | b64enc | quote }}
