apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vcluster-buildah-security.yaml
  - product-buildah-task.yaml
  - vcluster-image-build-product-pipeline.yaml
  - vcluster-image-build-product-pipelinerun.yaml
  - vcluster-image-build-task.yaml
  - vcluster-image-build-pipeline.yaml
  - vcluster-image-build-pipelinerun-v3.yaml
