apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-buildah
  namespace: infra
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: vcluster-buildah
priority: 20
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - SETFCAP
defaultAddCapabilities: null
requiredDropCapabilities:
  - MKNOD
  - KILL
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - runtime/default
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcluster-buildah-scc
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - vcluster-buildah
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcluster-buildah-scc
  namespace: infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcluster-buildah-scc
subjects:
  - kind: ServiceAccount
    name: vcluster-buildah
    namespace: infra
